[WIP] Remove pm2 from tests
marmelab/javascript-boilerplate pull request #143
Opened 2016-11-07 16:27 UTC by alexisjanvier

2016-11-09 09:50 UTC, Kmaschta commented
I'm clearly not in favor of `@` in the makefile. Theyl were removed with #135

2016-11-09 09:58 UTC, alexisjanvier commented on src/frontend/e2e/products.js
> +    this.timeout(150000);
debug spotted

2016-11-09 09:59 UTC, alexisjanvier commented
@Kmaschta I added `@`  only for `echo` ... I'm not sure this `echo` are realy useful for debugging?

2016-11-09 10:01 UTC, Kmaschta commented
Nope, you're right. I've just saw the travis build!

2016-12-11 09:24 UTC, djhi requested changes
This is neat :+1:

2016-12-11 09:24 UTC, djhi commented on package.json
> +    "koa-static": "next",
use the `3.0.0` release instead of next

2016-12-12 08:45 UTC, djhi approved these changes

2016-12-12 08:45 UTC, merged